services:
  - type: web
    name: pregnancy-tracker
    env: node
    buildCommand: echo "no build needed"
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
